export const env = {
    DATABASE_URL: process.env.DATABASE_URL!,
    AUTH_SECRET: process.env.AUTH_SECRET!,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID!,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET!,
    AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID!,
    AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET!,

    PUSHER_APP_ID: process.env.PUSHER_APP_ID!,
    PUSHER_SECRET: process.env.PUSHER_SECRET!,
    PUSHER_KEY: process.env.PUSHER_KEY!,
    PUSHER_CLUSTER: process.env.PUSHER_CLUSTER!,

    NEXT_PUBLIC_PUSHER_KEY: process.env.NEXT_PUBLIC_PUSHER_KEY!,
    NEXT_PUBLIC_PUSHER_CLUSTER: process.env.NEXT_PUBLIC_PUSHER_CLUSTER!,
};
